server:
  port: 8070

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/jtdb?jdbc:mysql://127.0.0.1:3306/jtdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
        username: root
        password: root

mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.jt.cart.pojo
  mapperLocations: classpath:mappers/*.xml
  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.jt.cart.mapper: debug
